name: kipa

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  intl: ^0.20.2
  flutter_portal: ^1.1.4
  get_it: ^9.2.0
  dio: ^5.9.0
  flutter_riverpod: ^3.2.0
  flutter_secure_storage: ^10.0.0
  pinput: ^6.0.1
  image_picker: ^1.2.1
  device_info_plus: ^11.1.1
  google_maps_flutter: ^2.14.0
  google_places_autocomplete_text_field: ^3.0.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.1
  web_socket_channel: ^3.0.3
  flutter_polyline_points: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/countries/